language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install coveralls
  - pip install .

# command to run tests, e.g. python setup.py test
script:
  - nosetests -v --with-coverage . smartdispatch/workers

after_success:
  - coveralls