#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import logging

from smartdispatch import sd_launch_pbs_script 

if __name__ == "__main__":
    logging.warn("This file is deprecated. The script 'sd-launch-pbs' should be use instead.")
    sd_launch_pbs_script.main()
