#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import logging
from smartdispatch import  smartdispatch_script


if __name__ == "__main__":
    
    logging.warn("This file is deprecated. The script 'smart-dispatch' should be use instead.")
    smartdispatch_script.main()
